import json
from fractions import Fraction
from pathlib import Path

from blooper import (
    A440,
    FLAT,
    KEYS,
    NATURAL,
    SHARP,
    Accent,
    Chord,
    Dynamic,
    Measure,
    Mixer,
    Note,
    Part,
    Pitch,
    Rest,
    Sampler,
    Synthesizer,
    record,
)

# Generate some samples to use for this example
directory = Path(__file__).parent / "samples"
directory.mkdir(exist_ok=True)
synths = [Synthesizer(wave="saw"), Synthesizer(wave="triangle")]
samples = []
for octave in range(2, 6):
    for pitch_class in "CDEFGAB":
        for symbol, accidental in (("♭", FLAT), ("♮", NATURAL), ("♯", SHARP)):
            pitch = Pitch(octave, pitch_class, accidental)
            frequency = A440.pitch_to_frequency(pitch)

            path = directory / f"{octave}{pitch_class}{symbol}-{frequency}.wav"

            if not path.exists():
                part = Part([[Note.new(Fraction(1, 1), pitch)]])
                record(path, Mixer.even(*[(synth, part) for synth in synths]))

            samples.append({"path": str(path), "frequency": frequency})

config = directory / "config.json"
with config.open("w") as stream:
    json.dump({"format": "wav", "samples": samples}, stream, indent=2, sort_keys=True)


# Use the sampler
sampler = Sampler.from_file(path=config)

high = Part(
    [
        [
            Note.new(Fraction(1, 4), Pitch(4, "F")),
            Note.new(Fraction(3, 16), Pitch(4, "A")),
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 16), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(4, "B")),
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(4, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(4, "F")),
            Note.new(Fraction(3, 16), Pitch(5, "C")),
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 16), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(5, "D")),
            Note.new(Fraction(1, 8), Pitch(5, "C")),
            Note.new(Fraction(1, 8), Pitch(4, "A")),
        ],
        [
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(5, "C")),
            Note.new(Fraction(1, 8), Pitch(5, "F")),
            Note.new(Fraction(1, 16), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(4, "E")),
            Note.new(Fraction(1, 16), Pitch(4, "E")),
            Note.new(Fraction(1, 8), Pitch(4, "C")),
            Note.new(Fraction(1, 8), Pitch(4, "G")),
            Note.new(Fraction(1, 8), Pitch(4, "F"), accent=Accent.SLUR),
        ],
        [
            Note.new(Fraction(1, 2), Pitch(4, "F")),
            Rest(Fraction(1, 2)),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(4, "F")),
            Note.new(Fraction(3, 16), Pitch(4, "A")),
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 16), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(4, "B")),
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(4, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(4, "F")),
            Note.new(Fraction(3, 16), Pitch(5, "C")),
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 16), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(5, "D")),
            Note.new(Fraction(1, 8), Pitch(5, "C")),
            Note.new(Fraction(1, 8), Pitch(4, "A")),
        ],
        [
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(5, "C")),
            Note.new(Fraction(1, 8), Pitch(5, "F")),
            Note.new(Fraction(1, 16), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(4, "E")),
            Note.new(Fraction(1, 16), Pitch(4, "E")),
            Note.new(Fraction(1, 8), Pitch(4, "C")),
            Note.new(Fraction(1, 8), Pitch(4, "G")),
            Note.new(Fraction(1, 8), Pitch(4, "F"), accent=Accent.SLUR),
        ],
        [
            Note.new(Fraction(1, 2), Pitch(4, "F")),
            Rest(Fraction(1, 2)),
        ],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [
            Note.new(Fraction(1, 4), Pitch(4, "F")),
            Note.new(Fraction(3, 16), Pitch(4, "A")),
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 16), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(4, "B")),
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(4, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(4, "F")),
            Note.new(Fraction(3, 16), Pitch(5, "C")),
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 16), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(5, "D")),
            Note.new(Fraction(1, 8), Pitch(5, "C")),
            Note.new(Fraction(1, 8), Pitch(4, "A")),
        ],
        [
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(5, "C")),
            Note.new(Fraction(1, 8), Pitch(5, "F")),
            Note.new(Fraction(1, 16), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(4, "E")),
            Note.new(Fraction(1, 16), Pitch(4, "E")),
            Note.new(Fraction(1, 8), Pitch(4, "C")),
            Note.new(Fraction(1, 8), Pitch(4, "G")),
            Note.new(Fraction(1, 8), Pitch(4, "F"), accent=Accent.SLUR),
        ],
        [
            Note.new(Fraction(1, 2), Pitch(4, "F")),
            Rest(Fraction(1, 2)),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(4, "F")),
            Note.new(Fraction(3, 16), Pitch(4, "A")),
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 16), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(4, "B")),
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(4, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(4, "F")),
            Note.new(Fraction(3, 16), Pitch(5, "C")),
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 16), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(5, "D")),
            Note.new(Fraction(1, 8), Pitch(5, "C")),
            Note.new(Fraction(1, 8), Pitch(4, "A")),
        ],
        [
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(5, "C")),
            Note.new(Fraction(1, 8), Pitch(5, "F")),
            Note.new(Fraction(1, 16), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(4, "E")),
            Note.new(Fraction(1, 16), Pitch(4, "E")),
            Note.new(Fraction(1, 8), Pitch(4, "C")),
            Note.new(Fraction(1, 8), Pitch(4, "G")),
            Note.new(Fraction(1, 8), Pitch(4, "F"), accent=Accent.SLUR),
        ],
        [
            Note.new(Fraction(1, 2), Pitch(4, "F")),
            Rest(Fraction(1, 2)),
        ],
        Measure(
            [
                Rest(Fraction(1, 8)),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "F"), Pitch(4, "A"), Pitch(5, "C")),
                    accent=Accent.STACCATO,
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "F"), Pitch(4, "A"), Pitch(5, "C")),
                ),
                Note.new(
                    Fraction(1, 16),
                    Chord(Pitch(4, "F"), Pitch(4, "A"), Pitch(5, "C")),
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "G"), Pitch(4, "B"), Pitch(5, "E")),
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "G"), Pitch(4, "B"), Pitch(5, "E")),
                ),
                Note.new(
                    Fraction(1, 16),
                    Chord(Pitch(4, "G"), Pitch(4, "B"), Pitch(5, "E")),
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "F"), Pitch(4, "B"), Pitch(5, "D")),
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "F"), Pitch(4, "B"), Pitch(5, "D")),
                ),
            ],
            accidentals={
                Fraction(1, 8): {"A": NATURAL},
                Fraction(3, 4): {"D": NATURAL},
            },
        ),
        Measure(
            [
                Rest(Fraction(1, 8)),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "F"), Pitch(4, "A"), Pitch(5, "C")),
                    accent=Accent.STACCATO,
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "F"), Pitch(4, "A"), Pitch(5, "C")),
                ),
                Note.new(
                    Fraction(1, 16),
                    Chord(Pitch(4, "F"), Pitch(4, "A"), Pitch(5, "C")),
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "G"), Pitch(4, "B"), Pitch(5, "E")),
                ),
                Note.new(
                    Fraction(1, 16),
                    Chord(Pitch(4, "G"), Pitch(4, "B"), Pitch(5, "E")),
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "F"), Pitch(4, "B"), Pitch(5, "D")),
                ),
                Note.new(
                    Fraction(1, 4),
                    Chord(Pitch(4, "F"), Pitch(4, "B"), Pitch(5, "D")),
                ),
            ],
            accidentals={
                Fraction(1, 8): {"A": NATURAL},
                Fraction(5, 8): {"D": NATURAL},
            },
        ),
        [
            Rest(Fraction(1, 8)),
            Note.new(
                Fraction(1, 8),
                Chord(Pitch(4, "D"), Pitch(4, "F"), Pitch(5, "A")),
            ),
            Note.new(
                Fraction(1, 8),
                Chord(Pitch(4, "D"), Pitch(4, "F"), Pitch(5, "A")),
            ),
            Note.new(
                Fraction(1, 8),
                Chord(Pitch(4, "D"), Pitch(4, "F"), Pitch(5, "A")),
            ),
            Note.new(
                Fraction(1, 16),
                Chord(Pitch(4, "D"), Pitch(4, "F"), Pitch(5, "A")),
            ),
            Note.new(
                Fraction(1, 8),
                Chord(Pitch(4, "E"), Pitch(4, "G"), Pitch(5, "B")),
            ),
            Note.new(
                Fraction(1, 8),
                Chord(Pitch(4, "E"), Pitch(4, "G"), Pitch(5, "B")),
            ),
            Note.new(
                Fraction(1, 8),
                Chord(Pitch(4, "E"), Pitch(4, "G"), Pitch(5, "B")),
            ),
            Note.new(
                Fraction(1, 16),
                Chord(Pitch(4, "E"), Pitch(4, "G"), Pitch(5, "B")),
            ),
        ],
        Measure(
            [
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "E"), Pitch(4, "G"), Pitch(5, "B")),
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "F"), Pitch(4, "A"), Pitch(5, "C")),
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "F"), Pitch(4, "A"), Pitch(5, "C")),
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "F"), Pitch(4, "A"), Pitch(5, "C")),
                ),
                Note.new(
                    Fraction(1, 16),
                    Chord(Pitch(4, "E"), Pitch(4, "G"), Pitch(5, "B")),
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "F"), Pitch(4, "A"), Pitch(5, "C")),
                ),
                Note.new(
                    Fraction(3, 16),
                    Chord(Pitch(4, "F"), Pitch(4, "A"), Pitch(5, "C")),
                ),
                Rest(Fraction(1, 8)),
            ],
            accidentals={
                Fraction(1, 8): {"A": NATURAL},
                Fraction(11, 16): {"A": FLAT},
            },
        ),
        Measure(
            [
                Rest(Fraction(1, 8)),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "F"), Pitch(4, "A"), Pitch(5, "C")),
                    accent=Accent.STACCATO,
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "F"), Pitch(4, "A"), Pitch(5, "C")),
                ),
                Note.new(
                    Fraction(1, 16),
                    Chord(Pitch(4, "F"), Pitch(4, "A"), Pitch(5, "C")),
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "G"), Pitch(4, "B"), Pitch(5, "E")),
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "G"), Pitch(4, "B"), Pitch(5, "E")),
                ),
                Note.new(
                    Fraction(1, 16),
                    Chord(Pitch(4, "G"), Pitch(4, "B"), Pitch(5, "E")),
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "F"), Pitch(4, "B"), Pitch(5, "D")),
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "F"), Pitch(4, "B"), Pitch(5, "D")),
                ),
            ],
            accidentals={
                Fraction(1, 8): {"A": NATURAL},
                Fraction(3, 4): {"D": NATURAL},
            },
        ),
        Measure(
            [
                Rest(Fraction(1, 8)),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "F"), Pitch(4, "A"), Pitch(5, "C")),
                    accent=Accent.STACCATO,
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "F"), Pitch(4, "A"), Pitch(5, "C")),
                ),
                Note.new(
                    Fraction(1, 16),
                    Chord(Pitch(4, "F"), Pitch(4, "A"), Pitch(5, "C")),
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "G"), Pitch(4, "B"), Pitch(5, "E")),
                ),
                Note.new(
                    Fraction(1, 16),
                    Chord(Pitch(4, "G"), Pitch(4, "B"), Pitch(5, "E")),
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "F"), Pitch(4, "B"), Pitch(5, "D")),
                ),
                Note.new(
                    Fraction(1, 4),
                    Chord(Pitch(4, "F"), Pitch(4, "B"), Pitch(5, "D")),
                ),
            ],
            accidentals={
                Fraction(1, 8): {"A": NATURAL},
                Fraction(5, 8): {"D": NATURAL},
            },
        ),
        [
            Rest(Fraction(1, 8)),
            Note.new(
                Fraction(1, 8),
                Chord(Pitch(4, "D"), Pitch(4, "F"), Pitch(5, "A")),
            ),
            Note.new(
                Fraction(1, 8),
                Chord(Pitch(4, "D"), Pitch(4, "F"), Pitch(5, "A")),
            ),
            Note.new(
                Fraction(1, 8),
                Chord(Pitch(4, "D"), Pitch(4, "F"), Pitch(5, "A")),
            ),
            Note.new(
                Fraction(1, 16),
                Chord(Pitch(4, "D"), Pitch(4, "F"), Pitch(5, "A")),
            ),
            Note.new(
                Fraction(1, 8),
                Chord(Pitch(4, "E"), Pitch(4, "G"), Pitch(5, "B")),
            ),
            Note.new(
                Fraction(1, 8),
                Chord(Pitch(4, "E"), Pitch(4, "G"), Pitch(5, "B")),
            ),
            Note.new(
                Fraction(1, 8),
                Chord(Pitch(4, "E"), Pitch(4, "G"), Pitch(5, "B")),
            ),
            Note.new(
                Fraction(1, 16),
                Chord(Pitch(4, "E"), Pitch(4, "G"), Pitch(5, "B")),
            ),
        ],
        Measure(
            [
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "E"), Pitch(4, "G"), Pitch(5, "B")),
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "F"), Pitch(4, "A"), Pitch(5, "C")),
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "F"), Pitch(4, "A"), Pitch(5, "C")),
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "F"), Pitch(4, "A"), Pitch(5, "C")),
                ),
                Note.new(
                    Fraction(1, 16),
                    Chord(Pitch(4, "E"), Pitch(4, "G"), Pitch(5, "B")),
                ),
                Note.new(
                    Fraction(1, 8),
                    Chord(Pitch(4, "F"), Pitch(4, "A"), Pitch(5, "C")),
                ),
                Note.new(
                    Fraction(3, 16),
                    Chord(Pitch(4, "F"), Pitch(4, "A"), Pitch(5, "C")),
                ),
                Rest(Fraction(1, 8)),
            ],
            accidentals={
                Fraction(1, 8): {"A": NATURAL},
                Fraction(11, 16): {"A": FLAT},
            },
        ),
        [
            Note.new(
                Fraction(1, 1),
                Chord(Pitch(3, "B"), Pitch(4, "E"), Pitch(4, "F")),
                dynamic=Dynamic.from_name("pianissimo"),
                accent=Accent.SLUR,
            ),
        ],
        [
            Note.new(
                Fraction(1, 1),
                Chord(Pitch(3, "B"), Pitch(4, "E"), Pitch(4, "F")),
                dynamic=Dynamic.from_name("pianissimo"),
            ),
        ],
        [],
        [],
        [],
        [],
        [],
        [
            Note.new(Fraction(1, 4), Pitch(5, "F"), accent=Accent.SLUR),
            Note.new(Fraction(3, 16), Pitch(5, "F")),
            Note.new(Fraction(1, 16), Pitch(5, "E"), accent=Accent.SLUR),
            Note.new(Fraction(1, 2), Pitch(5, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(5, "C"), accent=Accent.SLUR),
            Note.new(Fraction(3, 16), Pitch(5, "C")),
            Note.new(Fraction(1, 2), Pitch(4, "B")),
            Note.new(Fraction(1, 32), Pitch(5, "C")),
            Note.new(Fraction(1, 32), Pitch(4, "B")),
        ],
        [Note.new(Fraction(1, 1), Pitch(4, "F"))],
        [],
        [
            Note.new(Fraction(1, 4), Pitch(4, "F")),
            Note.new(Fraction(3, 16), Pitch(4, "A")),
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 16), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(4, "B")),
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(4, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(4, "F")),
            Note.new(Fraction(3, 16), Pitch(5, "C")),
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 16), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(5, "D")),
            Note.new(Fraction(1, 8), Pitch(5, "C")),
            Note.new(Fraction(1, 8), Pitch(4, "A")),
        ],
        [
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(5, "C")),
            Note.new(Fraction(1, 8), Pitch(5, "F")),
            Note.new(Fraction(1, 16), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(4, "E")),
            Note.new(Fraction(1, 16), Pitch(4, "E")),
            Note.new(Fraction(1, 8), Pitch(4, "C")),
            Note.new(Fraction(1, 8), Pitch(4, "G")),
            Note.new(Fraction(1, 8), Pitch(4, "F"), accent=Accent.SLUR),
        ],
        [
            Note.new(Fraction(1, 2), Pitch(4, "F")),
            Rest(Fraction(1, 2)),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(4, "F")),
            Note.new(Fraction(3, 16), Pitch(4, "A")),
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 16), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(4, "B")),
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(4, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(4, "F")),
            Note.new(Fraction(3, 16), Pitch(5, "C")),
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 16), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(5, "D")),
            Note.new(Fraction(1, 8), Pitch(5, "C")),
            Note.new(Fraction(1, 8), Pitch(4, "A")),
        ],
        [
            Note.new(Fraction(1, 8), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(5, "C")),
            Note.new(Fraction(1, 8), Pitch(5, "F")),
            Note.new(Fraction(1, 16), Pitch(4, "F")),
            Note.new(Fraction(1, 8), Pitch(4, "E")),
            Note.new(Fraction(1, 16), Pitch(4, "E")),
            Note.new(Fraction(1, 8), Pitch(4, "C")),
            Note.new(Fraction(1, 8), Pitch(4, "G")),
            Note.new(Fraction(1, 8), Pitch(4, "F"), accent=Accent.SLUR),
        ],
        [
            Note.new(Fraction(1, 2), Pitch(4, "F")),
            Rest(Fraction(1, 2)),
        ],
        [],
    ],
    key=KEYS["A♭ Major"],
)


low = Part(
    [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
            Note.new(Fraction(1, 16), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "F")),
            Rest(Fraction(1, 8)),
            Note.new(Fraction(1, 16), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(3, "F")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "D")),
            Note.new(Fraction(3, 16), Pitch(3, "D")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
            Note.new(Fraction(1, 16), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "E")),
            Rest(Fraction(1, 4)),
            Rest(Fraction(1, 16)),
            Note.new(Fraction(1, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(2, "B")),
            Note.new(Fraction(1, 8), Pitch(2, "A")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
            Note.new(Fraction(1, 16), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "F")),
            Rest(Fraction(1, 8)),
            Note.new(Fraction(1, 16), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(3, "F")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "D")),
            Note.new(Fraction(3, 16), Pitch(3, "D")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
            Note.new(Fraction(1, 16), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "E")),
            Rest(Fraction(1, 4)),
            Rest(Fraction(1, 16)),
            Note.new(Fraction(1, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(2, "B")),
            Note.new(Fraction(1, 8), Pitch(2, "A")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
            Note.new(Fraction(1, 16), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "F")),
            Rest(Fraction(1, 8)),
            Note.new(Fraction(1, 16), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(3, "F")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "D")),
            Note.new(Fraction(3, 16), Pitch(3, "D")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
            Note.new(Fraction(1, 16), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "E")),
            Rest(Fraction(1, 4)),
            Rest(Fraction(1, 16)),
            Note.new(Fraction(1, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(2, "B")),
            Note.new(Fraction(1, 8), Pitch(2, "A")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
            Note.new(Fraction(1, 16), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "F")),
            Rest(Fraction(1, 8)),
            Note.new(Fraction(1, 16), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(3, "F")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "D")),
            Note.new(Fraction(3, 16), Pitch(3, "D")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
            Note.new(Fraction(1, 16), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "E")),
            Rest(Fraction(1, 4)),
            Rest(Fraction(1, 16)),
            Note.new(Fraction(1, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(2, "B")),
            Note.new(Fraction(1, 8), Pitch(2, "A")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
            Note.new(Fraction(1, 16), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "F")),
            Rest(Fraction(1, 8)),
            Note.new(Fraction(1, 16), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(3, "F")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "D")),
            Note.new(Fraction(1, 4), Pitch(3, "D")),
            Note.new(Fraction(1, 4), Pitch(2, "E")),
            Note.new(Fraction(1, 4), Pitch(3, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(1, 4), Pitch(3, "F")),
            Rest(Fraction(1, 16)),
            Note.new(Fraction(1, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(2, "A")),
            Note.new(Fraction(1, 8), Pitch(2, "G")),
            Note.new(Fraction(1, 8), Pitch(2, "F")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
            Note.new(Fraction(1, 16), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "F")),
            Rest(Fraction(1, 8)),
            Note.new(Fraction(1, 16), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(3, "F")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "D")),
            Note.new(Fraction(1, 4), Pitch(3, "D")),
            Note.new(Fraction(1, 4), Pitch(2, "E")),
            Note.new(Fraction(1, 4), Pitch(3, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(1, 4), Pitch(3, "F")),
            Rest(Fraction(1, 16)),
            Note.new(Fraction(1, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(2, "A")),
            Note.new(Fraction(1, 8), Pitch(2, "G")),
            Note.new(Fraction(1, 8), Pitch(2, "F")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
            Note.new(Fraction(1, 16), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
            Note.new(Fraction(1, 16), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F"), accent=Accent.STACCATO),
            Rest(Fraction(1, 4)),
            Rest(Fraction(1, 16)),
            Note.new(Fraction(1, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(2, "B")),
            Note.new(Fraction(1, 8), Pitch(2, "A")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
            Note.new(Fraction(1, 16), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "D")),
            Rest(Fraction(1, 8)),
            Note.new(Fraction(1, 16), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(3, "F")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
            Note.new(Fraction(1, 16), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Rest(Fraction(1, 4)),
            Rest(Fraction(1, 16)),
            Note.new(Fraction(1, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(2, "B")),
            Note.new(Fraction(1, 8), Pitch(2, "A")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
            Note.new(Fraction(1, 16), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "D")),
            Rest(Fraction(1, 8)),
            Note.new(Fraction(1, 16), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(3, "F")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
            Note.new(Fraction(1, 16), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Rest(Fraction(1, 4)),
            Rest(Fraction(1, 16)),
            Note.new(Fraction(1, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(2, "B")),
            Note.new(Fraction(1, 8), Pitch(2, "A")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
            Note.new(Fraction(1, 16), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "D")),
            Rest(Fraction(1, 8)),
            Note.new(Fraction(1, 16), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(3, "F")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
            Note.new(Fraction(1, 16), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Rest(Fraction(1, 4)),
            Rest(Fraction(1, 16)),
            Note.new(Fraction(1, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(2, "B")),
            Note.new(Fraction(1, 8), Pitch(2, "A")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
            Note.new(Fraction(1, 16), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "D")),
            Rest(Fraction(1, 8)),
            Note.new(Fraction(1, 16), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(3, "F")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Note.new(Fraction(3, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
            Note.new(Fraction(1, 16), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "C")),
            Note.new(Fraction(1, 8), Pitch(3, "E")),
            Note.new(Fraction(1, 8), Pitch(2, "E")),
        ],
        [
            Note.new(Fraction(1, 4), Pitch(2, "F")),
            Rest(Fraction(1, 4)),
            Rest(Fraction(1, 16)),
            Note.new(Fraction(1, 16), Pitch(3, "F")),
            Note.new(Fraction(1, 8), Pitch(3, "C")),
            Note.new(Fraction(1, 8), Pitch(2, "B")),
            Note.new(Fraction(1, 8), Pitch(2, "A")),
        ],
        [Note.new(Fraction(1, 4), Pitch(2, "F"))],
    ],
    key=KEYS["A♭ Major"],
)

record(Path("sample.wav"), Mixer.even((sampler, high), (sampler, low)))
